fix: next config/env loading
toomuchdesign/next-page-tester pull request #152
Opened 2021-02-17 08:11 UTC by Meemaw

## What kind of change does this PR introduce?

Fixes the way (order) in which we load environment variables.

Fixes https://github.com/toomuchdesign/next-page-tester/issues/151

## What is the current behaviour?

We load next config before we load base environment variables. This was due to the reason that when we called `setEnvVars` we expected next config to be loaded already. So we had a dependency cycle in which we couldn't  set env vars before loading next config.

## What is the new behaviour?

We load base environment variables (dotenv + runtime) before loading next config. After that we have all the variables available for the `next.config.js` to load properly.

After, in `setEnvVars` we just merge in the additional env vars coming from `next.config.js` itself.

## Does this PR introduce a breaking change?

No

## Other information:

## Please check if the PR fulfills these requirements:

- [x] Tests for the changes have been added
- [ ] Docs have been added / updated

2021-02-17 08:12 UTC, Meemaw commented on src/__tests__/environment-variables/environment-variables.test.tsx
> -            NAME_CLASH_RUNTIME_VS_CONFIG_VS_DOTFILE: 'FROM_CONFIG',
Looking at this test it seems our env loading didn't work properly before. We are doing client `render` and we got all the variables into the DOM (including those not prefixed with `NEXT_PUBLIC_`)

2021-02-17 21:58 UTC, toomuchdesign requested changes
Hi @Meemaw,
I'm submitting a request change because I feel like the way I understood environment variables in Next.js are different then what I see here and I'd like to clarify my assumptions with you.

First, I really like the way you rearranged env var tests 👍 

My point concerns client runtime. Server runtime seems ok to me. Maybe I'll double check it later.

In regard of client runtime I though that the `NEXT_PUBLIC_` prefix filtering happened only for those env vars declared in dotenv files. I would expect any other var coming from runtime or config file to be available also in client runtime.

I've done a quick check and It seems to work like this to me. Would mind double checking and help me clarify this point?

Maybe we could rename client runtime as something like public runtime or browser runtime?

2021-02-18 11:05 UTC, Meemaw commented
Hey @toomuchdesign 

I've did some research and came up with following findings running next server:

```js
DOMAIN_FROM_RUNTIME:
NEXT_PUBLIC_DOMAIN_FROM_RUNTIME: NEXT_PUBLIC_DOMAIN_FROM_RUNTIME
DOMAIN_FROM_CONFIG: DOMAIN_FROM_CONFIG
NEXT_PUBLIC_DOMAIN_FROM_CONFIG: NEXT_PUBLIC_DOMAIN_FROM_CONFIG
DOMAIN_FROM_DOTFILE:
NEXT_PUBLIC_DOMAIN_FROM_DOTFILE: NEXT_PUBLIC_DOMAIN_FROM_DOTFILE
```

Based on this it seems that `NEXT_PUBLIC_` filtering happens for dotenv vars + runtime vars, but not for vars coming from config.

2021-02-20 22:40 UTC, toomuchdesign approved these changes

2021-02-21 06:25 UTC, merged