feat: render document in server context
toomuchdesign/next-page-tester pull request #78
Opened 2020-12-28 15:12 UTC by Meemaw

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behaviour?

You can also link to an open issue here.

## What is the new behaviour?

...

## Does this PR introduce a breaking change?

What changes might users need to make in their application due to this PR?

## Other information:

## Please check if the PR fulfills these requirements:

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

2020-12-28 15:13 UTC, Meemaw commented on src/utils.ts
> +      jest.mock('react', () => React);
To avoid warnings with different versions of `React` being used.

2020-12-28 15:14 UTC, Meemaw commented
Related to https://github.com/toomuchdesign/next-page-tester/pull/76

2020-12-28 15:25 UTC, Meemaw commented on src/__tests__/global-object/global-object.test.tsx
> +            component_runTime_document: true, // TODO: should be false
Not sure if possible because `render` is called after `getPage` by the `@testing-library/react`

2020-12-28 18:17 UTC, toomuchdesign requested changes
I left a few indications for possible request changes, overall looks very good to me. 👍 
This was definitely missing in my original implementation.

I'm a bit sad for the workaround made necessary to have the same React instance running, but it's something I felt would have popped up sooner or later.

Shall we also cover custom App component with `global-object` tests of it'd be overkill?

2020-12-28 19:19 UTC, toomuchdesign commented
I added a commit which avoids calling `jest.mock` to mutate `next/document` return object. I moved the mocking to `testHelpers` in plain hackish CommonJS JS.

Feel free to remove/change this commit if you come up with a better solution.

2020-12-29 08:33 UTC, Meemaw commented on src/__tests__/global-object/global-object.test.tsx
> +          ).toEqual({
Done

2020-12-29 08:34 UTC, Meemaw commented on src/__tests__/global-object/global-object.test.tsx
> +    describe('useDocument=true', () => {
I nested it cause it falls under SSR; fell free to move it per your preferences.

2020-12-29 13:24 UTC, toomuchdesign commented
⚠️ I just rebased this branch against master.

2020-12-30 10:27 UTC, toomuchdesign approved these changes

2020-12-30 10:49 UTC, Meemaw commented
I'll merge this and try to get https://github.com/toomuchdesign/next-page-tester/pull/76 working with the latest updates.

2020-12-30 10:49 UTC, merged